name: Container

on:
  - push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: kryz81/posts:latest
        ports:
          - 3000:3000
        env:
          PORT: 4000
      db:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Ping app
        run: |
          curl http://localhost:3000