name: Container

on:
  - push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: kryz81/myapp:1.4.0
        ports:
          - 3000:3000
      db:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Ping app
        run: |
          curl http://localhost:3000